name: 'Get and install dependencies'
description: 'seprating common steps'
runs:
  using: 'composite'
  steps:
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Create cache
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash 
