name: Output
on:
  issues:
    types:
      - opened
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - env:
          ISSUE_NO: ${{ github.event.issue.number }}
        run: echo $ISSUE_NO
